### ISSUE TITLE
Add odysee.com 

### ISSUE THREAD

**Issue by vehosah** [polymorphicshade/NewPipe#139]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### What feature do you want?
I would love to be able to access odysee.com by using newpipe 

#### Why do you want this feature?
Because it is better than youtube, it is open source, and it doesn't have ads

**Comment by Atemu** [comment]
> [ ] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream. 

?

**Comment by vehosah** [comment]
> > [ ] This feature is related to sponsor or ad blocking and/or has explicitly been rejected upstream.
> 
> ?

I fixed it

**Comment by Atemu** [comment]
Could you link the rejection?

**Comment by vehosah** [comment]
> Could you link the rejection?

https://github.com/TeamNewPipe/NewPipe/issues/4854

**Comment by vehosah** [comment]
> Could you link the rejection?

And this one https://github.com/TeamNewPipe/NewPipe/issues/6645

**Comment by Atemu** [comment]
The feature request was closed because it's in the wrong place.

https://github.com/TeamNewPipe/NewPipeExtractor/issues/434

**Comment by vehosah** [comment]
Actually I doubt that they are going to add it because they say that it's a place for misinformation

**Comment by Atemu** [comment]
That is a very good reason though I personally doubt they'd be against it if someone came and implemented it. To that, please read the issue template:

> This is not the place for stale upstream feature requests.

I don't follow the platform but if they rejected support because the platform primarily consists of misinformation and other societal cancer, I don't think we'd decide any differently but I obviously can's speak for @polymorphicshade.

**Comment by polymorphicshade** [comment]
While I'm personally anti-censorship, and while I have no objections to adding odysee.com to NewPipe, this would require a change to the NewPipeExtractor which I have not forked.

I'm closing this issue because I have no plans on forking the extractor.

Though I do hope upstream NewPipe adds sites like this in the future. I think restricting access to internet resources based on the potential of misinformation sets a dangerous precedent.
