### ISSUE TITLE
While it still doesn't show up on f-droid, can it include a self update installation and notification?

### ISSUE THREAD

**Issue by je-vv** [polymorphicshade/NewPipe#14]
I would like this fork to be found on f-droid.  There's a github issue already about that (my only take is that I would prefer the official f-droid).  But while it's not there (perhaps it'll be required to also change the name a bit, and there's another github issue about it), the app can sel update, sending a notification, and then the user can tap over it to get the update, just like Signal and ApkGrabber do when you download their apps from their web pages.

**Comment by najodleglejszy** [comment]
the Github version of Newpipe already does that, so I assume it wouldn't be that difficult to bring it over.

**Comment by 07416** [comment]
Was the self-update option removed from the settings when the app was forked (obviously it should until the feature points to this repo)?

**Comment by grravity** [comment]
To my knowledge the reason original newpipe wasn't only on fdroid is because when youtube breaks it it takes them like a week for fdroid to push the update meanwhile the app is unusable during that period.

So newpipe added an unofficial repo

I think if we got it on the official repo that'd be great and I see no reason not to, but I also think we should get a custom repo setup if possible, or maybe Izzy's repo (idk how fast Izzy updates).

Also yeah I don't think I'm getting update notifications for the apk either, so I think that needs to be pointed to this git repo.

**Comment by polymorphicshade** [comment]
Update notifications that look at the releases for this fork should now be functional in release [v0.20.6_r3](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.6_r3).
