### ISSUE TITLE
Keep Android 4.4 (KitKat) as a minimum requirement

### ISSUE THREAD

**Issue by highbaser** [polymorphicshade/NewPipe#188]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Keep this fork compatible with Android 4.4 (KitKat) API level 19. 

### Why do you want this feature?

There are still smartphones running Android below 5.X (Lollipop) and NewPipe is the only full-featured Youtube (and SoundCloud) alternative. Corporate giants don't support these devices as they want us to buy new ones even if an old device is still functional.

### Why ist the feature relevant to this fork?

NewPipe developers seem to have started falling into _the older the less secure_ and the _if vendor doesn't support it we shouldn't do that either_ mind traps. They're [phasing out Android 4.4+ support](https://github.com/TeamNewPipe/NewPipe/issues/7602) and moving towards Android 5.0 as a minimum requirement. They fail to understand that for users without skills of installing custom ROMs (that would also break many things and lose a lot of functionality) NewPipe is the **only full-featured alternative** for official Youtube and SoundCloud apps.

**Comment by Atemu** [comment]
> There are still smartphones running Android below 5.X (Lollipop)

If the manufacturer stopped supporting it *over 7 years ago* and nobody ported a custom ROM to it, these are dead and e-waste. It's unfortunate and shitty but that's how it is.

> NewPipe developers seem to have started falling into the older the less secure and the if vendor doesn't support it we shouldn't do that either mind traps.

It's not a mind-trap, it's reality. There is a non-zero amount of effort required to stay compatible with ancient, obsolete versions of software. See the thread you linked for examples.  
You can't expect volunteers to do that for you. Even if you (or somebody else) stepped up to keep support going, this is something that affects everyone. Any new feature developed would have to be tweaked for compatibility with some shitty old OS that nobody should use anymore to the detriment of nearly everyone else who use relatively recent OSs. 

Supporting ancient versions of software is never a sustainable model.

> They fail to understand that for users without skills of installing custom ROMs (that would also break many things and lose a lot of functionality) NewPipe is the only full-featured alternative for official Youtube and SoundCloud apps.

They don't. They're fully aware. It's simply not something you can expect them to care a whole lot about.

If you don't have the "skills" required to install a custom ROM, you need to buy a new phone. It's that simple. That's how the world works unfortunately.

**Comment by polymorphicshade** [comment]
I'm not going to do this. Doing something like this would be a very annoying to maintain, not to mention all the possible security risks.

**Comment by highbaser** [comment]
> If the manufacturer stopped supporting it over 7 years ago and nobody ported a custom ROM to it, these are dead and e-waste.

No, they aren't. They are still functional, they still do work and can run applications perfectly built against the proper API level. Calling that e-waste is nothing more than supporting consumerism and throwaway society.

> Any new feature developed would have to be tweaked for compatibility with some shitty old OS that nobody should use anymore to the detriment of nearly everyone else who use relatively recent OSs.

For Android, there are well-known methods of staying compatible with an old API. You also have to stay compatible with a lot of things, besides Android API that requires work. API is just one thing. You talk about backporting as if it was a sin or something really really wrong. On the first place you need the same amount of work (or a lot not more) when you're forward-porting your codebase (e.g. when a new Android version comes in). Older OSes are not "shitty" black boxes that are unknown to anyone. They are well-known platforms with a well-documented API. There are also more experience collected on websites and forums than about brand new OSes.

> Supporting ancient versions of software is never a sustainable model.

On the contrary. It's the only sustainable model if there are no custom ROMs, that would also needed to be optimized for that hardware and that would be a lot more work. And by sustainabiliy I mean keeping and using a device that works.

> If you don't have the "skills" required to install a custom ROM, you need to buy a new phone. It's that simple. That's how the world works unfortunately.

You're talking about custom ROMs as if they were full-featured and always better, faster and more lightweight than original ROMs. They aren't. There are some cases when they are (like LineageOS for officially supported devices) but mostly they aren't. In this case you have two choices.
* Spend a lot of time finding, testing (or even building) and installing a custom ROM without the promise it would be full-featured.
* Continue using the original ROM that is full-featured.

There are many reasons not to use custom ROMs but keep using the original legacy ROM with Play Store and all vendor bloatware disabled and custom apps (like NewPipe) installed.

If you're giving an alternative to Youtube, you should also think about giving an alternative to obsolescence driven by OS deprecation. If you dislike ads and sponsored content so much that you forked NewPipe to ship with SponsorBlock support, you must dislike consumerism as well. That's why it would make sense to have changes backported to KitKat.

**Comment by Atemu** [comment]
> They are still functional

The hardware is, the software isn't. If the software were to be supported aswell, yeah it wouldn't be e-waste. Unfortunately, that's not the case.

> applications perfectly built against the proper API level.

It's not "proper", it's "ancient". Targeting an ancient API level has big implications.

> Calling that e-waste is nothing more than supporting consumerism and throwaway society.

It's reality. Whether you want it or not, that's the world we find ourselves in. I don't like it either but that's how it is.

> For Android, there are well-known methods of staying compatible with an old API. You also have to stay compatible with a lot of things, besides Android API that requires work. API is just one thing. You talk about backporting as if it was a sin or something really really wrong.

There's nothing wrong with staying compatible with a few older versions but there is a point where the "older version" becomes a "legacy version", is effectively unsupported and becomes a maintenance burden.

> On the first place you need the same amount of work (or a lot not more) when you're forward-porting your codebase (e.g. when a new Android version comes in).

That work brings more features, simpler interactions and new possibilities.

All the work on staying backwards compatible does is to keep ancient platforms working, often in compromised manners and often in manners that compromise new platforms.

> Older OSes are not "shitty" black boxes that are unknown to anyone. They are well-known platforms with a well-documented API. There are also more experience collected on websites and forums than about brand new OSes.

That doesn't change the fact that they're undesirable to support when all the newer OS versions have moved on to better ways of doing things.

> It's the only sustainable model if there are no custom ROMs, that would also needed to be optimized for that hardware and that would be a lot more work. And by sustainabiliy I mean keeping and using a device that works.

I am speaking about sustainability in the context of software, not hardware. It's obviously unsustainable to throw away working hardware.

The problem here is the lack of OS support for the old hardware, not app support for OSs because if the old hardware was supported by the OS, there would be no need for any app to support an old OS.

It's a lot more sustainable to keep an OS working on older hardware than software working with old OSs. This is due to the fact that hardware hasn't changed a whole lot in the past few decades (other than get more efficient/faster) while software is radically different now than it was 5 years ago.

> There are many reasons not to use custom ROMs but keep using the original legacy ROM with Play Store and all vendor bloatware disabled and custom apps (like NewPipe) installed.

Yeah, nothing wrong with that.

Problem is that you're unlikely to receive any support for the ROM from its original vendor.

> If you're giving an alternative to Youtube, you should also think about giving an alternative to obsolescence driven by OS deprecation.

Those two goals are only related tangentially, if at all.

> If you dislike ads and sponsored content so much that you forked NewPipe to ship with SponsorBlock support, you must dislike consumerism as well.

I can't speak for poly but I certainly dislike it.

I don't agree that keeping obsolete software "alive" is in any way a good way counter it however. 

Software has practically no physical cost, so "Softwre consumerism" (throwing away old software to replace it with new software) is simply not harmful; quite the opposite if you ask me.  
Making physical hardware obsolete by dropping OS support is extremely harmful however.
