### ISSUE TITLE
hdr 

### ISSUE THREAD

**Issue by bingoxo** [polymorphicshade/NewPipe#32]
the only thing that vanced has and newpipe doesnt

**Comment by polymorphicshade** [comment]
While this would be great, I will not be looking to to this - this is because it is already being worked on in the Extractor side of things (this fork does not include a fork for the Extractor).

Once the official NewPipe devs add HDR support to the Extractor, then it will be easy to include that in this fork.

For more information, see here:
https://github.com/TeamNewPipe/NewPipeExtractor/issues/39

I'm going to close this issue since there isn't much I can do about it, other than wait for the NewPipe devs to include this in the Extractor.
