### ISSUE TITLE
Release 0.25.1

### ISSUE THREAD

**Issue by PimpinPumpkin** [polymorphicshade/NewPipe#323]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/polymorphicshade/NewPipe/issues) or [closed](https://github.com/polymorphicshade/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I'm aware that this is a request for NewPipe itself and that requests for adding a new service need to be made at [NewPipeExtractor](https://github.com/TeamNewPipe/NewPipeExtractor/issues).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/polymorphicshade/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Feature description

Upstream Newpipe 0.25.1 was released.

### Why do you want this feature?

Latest and greatest features!

### Why ist the feature relevant to this fork?

Keeping the project up to date.

**Comment by gsture** [comment]
Is this project still maintained or do we have to migrate to the main version of newpipe? Looking forward to an update.

**Comment by lsomm** [comment]
@gsture I think it is still maintained, but the maintainer has little free time. See [this reply](https://github.com/polymorphicshade/NewPipe/issues/301#issuecomment-1427111358). 

Edit 1: Also 0.25.1 is just a dot release with a minimum of new features and mostly bugfixes. So this might not be super high priority, especially with limited ressources  and if no one on this fork is experiencing any bugs fixed by 0.25.1.

Edit 2: He just merged 5 commits 45mins ago. I think your worries of this being unmaintained are unwarrented :wink:.

**Comment by PimpinPumpkin** [comment]
Yay, 0.25.1 just merged!
