### ISSUE TITLE
Project paused/stalled/abandoned?

### ISSUE THREAD

**Issue by HarriBuh** [polymorphicshade/NewPipe#370]
Since I like this project very much I'm kinda disappointed about the lack of development since August 2023. I would like to know whether I should change to other, actively developed apps of the same kind or not.

**Comment by Atemu** [comment]
There has not been an upstream NewPipe release since August: https://github.com/TeamNewPipe/NewPipe/releases

The Sponsorblock part is pretty much feature-complete. There's one minor thing not working quite right and, as always, you could do more but nothing that warrants immediate intervention for the app to remain useful.

What kind of development do you think you're entitled to here?
