### ISSUE TITLE
Closing active full screen video from Notiification is enabling tablet ui even though Disable table UI is turned on

### ISSUE THREAD

**Issue by Raul1198** [polymorphicshade/NewPipe#43]
### Checklist

- [x] I am using the latest version - v0.20.10 R5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video
2.  go to full screen 
3.  pull down your notification panel
4.  close the playing video from the notification panel by pressing the X button in Newpipe's playing Notification

### Actual behaviour

stop the video and ui is in tablet mode (though Disable Tablet UI is enabled ) and have to enable auto rotation to make to back to portrait way

### Expected behavior

back to portrait video ui

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/29801315/109967435-6a88c480-7d17-11eb-8ca6-d21ace04148c.mp4

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: redmi k20 pro

**Comment by polymorphicshade** [comment]
In the [latest relaese](https://github.com/polymorphicshade/NewPipe/releases/tag/v0.20.11_r2), I've removed the Disable Tablet/TV extra settings because they were causing a lot of domino-effect issues. I'm going to close this issue until I discover a better way to prevent Android from choosing a layout based on screen dimensions.
