### ISSUE TITLE
Add "Local Media Files" tab in drawer once the media player is stable

### ISSUE THREAD

**Issue by SameenAhnaf** [polymorphicshade/NewPipe#52]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want

Newpipe has an amazing media player built-in. Unfortunately, we can't play other media files with this player. I wish to have "Local Media Files" tab in drawer once the media player is stable. Plus, this tab should have separate drawers for "Video" and "Audio" sections to avoid mix-up.

**Comment by polymorphicshade** [comment]
I won't be doing this. There are plenty of other apps designed to be local media players.

**Comment by SameenAhnaf** [comment]
@polymorphicshade Sorry for the disturbance. But, here are my few words to say.

I respect your time, efforts and dedication to this app. Staying up-to-date with an app bringing necessary features is a really tough job. But would you please reconsider adding this tab? I don't need support for all file types. Only, Newpipe supported (for download and streaming) formats.

Thanks in advance for your dedication!

**Comment by barolo** [comment]
> I won't be doing this. There are plenty of other apps designed to be local media players.

Since it already plays downloaded files would it be hard to expose the player to the system [ I might have asked it already somewhere but cannot find it now ].
There's nothing else that has such a great implementation of skip silence unfortunately.

**Comment by Atemu** [comment]
This is a great idea and something I've been wanting aswell but, why are you asking for it here? This fork is concerned with SponsorBlock and not much else.

Go suggest this feature upstream. We have all the features they have + SponsorBlock + some small extras.

When this has been implemented upstream, we can think about SponsorBlock-specific adaptations, i.e. sponsor skipping in downloaded videos if they come from youtube.

Feel free to ping me in the upstream issue.

**Comment by SameenAhnaf** [comment]
@Atemu What should I do? I was actually suggested to use Sponsorblock fork as stated in https://github.com/TeamNewPipe/NewPipe/issues/5666#issuecomment-785394793 ? Will I reopen that issue?

**Comment by Atemu** [comment]
@SameenAhnaf, @MD77MD didn't mean that you should close the issue, I think they meant that poly had implemented something similar before and might be able to lend a hand in implementing it *upstream*.

This fork only exists because upstream explicitly decided against having SponsorBlock functionality and there's nothing indicating that the same is true for this feature. Just re-open the upstream issue.

**Comment by barolo** [comment]
> This is a great idea and something I've been wanting aswell but, why are you asking for it here? This fork is concerned with SponsorBlock and not much else.
> 
> Go suggest this feature upstream. We have all the features they have + SponsorBlock + some small extras.
> 
> When this has been implemented upstream, we can think about SponsorBlock-specific adaptations, i.e. sponsor skipping in downloaded videos if they come from youtube.
> 
> Feel free to ping me in the upstream issue.

If I'm recalling correctly, current ability of this fork to play downloaded files stemmed from my initial request of playing local files which got rejected upstream.

**Comment by Atemu** [comment]
Your link is broken.

**Comment by barolo** [comment]
> Your link is broken.

It is not, but just in case: `https://github.com/polymorphicshade/NewPipe/issues/23`

**Comment by SameenAhnaf** [comment]
@barolo TeamNewpipe/Newpipe#5666 is already open. No need to talk about this in this repository any more. Mainstream Newpipe has more users. So, it should atteact most devs' attention.

**Comment by barolo** [comment]
> @barolo [TeamNewPipe#5666](https://github.com/TeamNewPipe/NewPipe/issues/5666) is already open. No need to talk about this in this repository any more. Mainstream Newpipe has more users. So, it should atteact most devs' attention.

Thank you for letting me know, it was created after another such request got closed/rejected by one of the devs.

**Comment by barolo** [comment]
[JustPlayer](https://github.com/moneytoo/Player) got this feature implemented recently so I officially don't care any-longer, it's not as good [doesn't fast-forward just cuts] but it's good enough for me.
Hopefully will be improved over time.

**Comment by iamashwin99** [comment]
for those who really need the video player to work, here's a trick to get a specific file to appear in the downloads section if you have root permission.
Open the file /data/data/org.polymorphicshade.newpipe/databases/downloads.db in a SQL editor( I suggest MiXplorer) add a new entry with the path to the video file, a random youtube URL, a random byte count, a random epoch time stamp, and the kind as 'v' for video and 'a' for audio, set the segments as NULL. (See the image below for a better idea).
![image](https://user-images.githubusercontent.com/46030335/163701908-e514481f-aef3-408c-a05c-0eea247e7c8c.png)

 Now save the database, and restart the app. and you should see the local video in the download section,

the down side of this method is that you have to change the video path manually, and you miss out on fast forward, brightness control, speed control etc.. I would still think that it would be easier to implement a "share" or "open with" dialogue for the app so that we could use some local explorer and "share" the video to newpipe. This would be easier to implement than adding a tab in the drawer and would solve most of the requirements of users of this thread. Although Im no app developer, so not sure if my guess is correct.
