### ISSUE TITLE
Is it possible to merge in changes automatically?

### ISSUE THREAD

**Issue by dbenjaminmiller** [polymorphicshade/NewPipe#82]
The new version of NewPipe fixes a major extractor bug and gets rid of a lot of the throttling problems that were often an issue recently. Additionally, many quick-fix versions have been necessary in the past. The sponsorblock capabilities of this fork are great, but could it be potentially possible to effectively maintain it as a series of patches so that it could be rebased on new versions from upstream with few issues? Or, alternatively, and equivalently, has it been found that merging in upstream changes generally works pretty well? I can test building the latest version with upstream patches tonight and send a PR if it works. Is that appreciated?

**Comment by ajayyy** [comment]
If you are looking for something easier to do automatically, you could update only the newpipe extractor dependency, and not the code itself.

**Comment by Atemu** [comment]
Merge conflicts arise because of diversion, not because you do merging vs. rebasing. Rebasing will face the same conflicts as merging. We effectively maintain a series of patches already.

You don't need automation for merging trivial changes on every upstream stable release - that's just a single command with git or two button presses with magit. Merge conflicts are the issue and those obviously can't be solved automatically.

**Comment by dbenjaminmiller** [comment]
I understand that --- sorry, my question more was how much divergence 
there generally was.

Aug 4, 2021 04:24:41 Atemu ***@***.***>:

**Comment by Atemu** [comment]
Depends on what upstream did in that time. Changes that touch the player implementation, strings and a few crash reporting related things usually cause a conflict because we differ here.  
Anything else is usually of no relevance.

**Comment by polymorphicshade** [comment]
From all the merges I've done, a large majority of them had merge conflicts. Not necessarily complex ones, but nonetheless require manual resolution.
